version: '3.1'

services:
  postgres:
    image: 'postgres:latest'
    environment:
        - 'POSTGRES_USER=postgres'
        - 'POSTGRES_DB=postgres'
        - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
